#
# Autogenerated by Thrift Compiler (1.0.0-dev)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING


module HS2

using Thrift
import Thrift.process, Thrift.meta, Thrift.distribute




export meta
export TProtocolVersion # enum
export TTypeId # enum
export TStatusCode # enum
export TOperationState # enum
export TOperationType # enum
export TGetInfoType # enum
export TFetchOrientation # enum
export TTypeEntryPtr # typealias for Int32
export TIdentifier # typealias for AbstractString
export TPattern # typealias for AbstractString
export TPatternOrIdentifier # typealias for AbstractString
export TTypeQualifierValue # struct
export TTypeQualifiers # struct
export TPrimitiveTypeEntry # struct
export TArrayTypeEntry # struct
export TMapTypeEntry # struct
export TStructTypeEntry # struct
export TUnionTypeEntry # struct
export TUserDefinedTypeEntry # struct
export TTypeEntry # struct
export TTypeDesc # struct
export TColumnDesc # struct
export TTableSchema # struct
export TBoolValue # struct
export TByteValue # struct
export TI16Value # struct
export TI32Value # struct
export TI64Value # struct
export TDoubleValue # struct
export TStringValue # struct
export TColumnValue # struct
export TRow # struct
export TBoolColumn # struct
export TByteColumn # struct
export TI16Column # struct
export TI32Column # struct
export TI64Column # struct
export TDoubleColumn # struct
export TStringColumn # struct
export TBinaryColumn # struct
export TColumn # struct
export TRowSet # struct
export TStatus # struct
export THandleIdentifier # struct
export TSessionHandle # struct
export TOperationHandle # struct
export TOpenSessionReq # struct
export TOpenSessionResp # struct
export TCloseSessionReq # struct
export TCloseSessionResp # struct
export TGetInfoValue # struct
export TGetInfoReq # struct
export TGetInfoResp # struct
export TExecuteStatementReq # struct
export TExecuteStatementResp # struct
export TGetTypeInfoReq # struct
export TGetTypeInfoResp # struct
export TGetCatalogsReq # struct
export TGetCatalogsResp # struct
export TGetSchemasReq # struct
export TGetSchemasResp # struct
export TGetTablesReq # struct
export TGetTablesResp # struct
export TGetTableTypesReq # struct
export TGetTableTypesResp # struct
export TGetColumnsReq # struct
export TGetColumnsResp # struct
export TGetFunctionsReq # struct
export TGetFunctionsResp # struct
export TGetOperationStatusReq # struct
export TGetOperationStatusResp # struct
export TCancelOperationReq # struct
export TCancelOperationResp # struct
export TCloseOperationReq # struct
export TCloseOperationResp # struct
export TGetResultSetMetadataReq # struct
export TGetResultSetMetadataResp # struct
export TFetchResultsReq # struct
export TFetchResultsResp # struct
export TGetDelegationTokenReq # struct
export TGetDelegationTokenResp # struct
export TCancelDelegationTokenReq # struct
export TCancelDelegationTokenResp # struct
export TRenewDelegationTokenReq # struct
export TRenewDelegationTokenResp # struct
export PRIMITIVE_TYPES # const
export COMPLEX_TYPES # const
export COLLECTION_TYPES # const
export TYPE_NAMES # const
export CHARACTER_MAXIMUM_LENGTH # const
export PRECISION # const
export SCALE # const
export TCLIServiceProcessor, TCLIServiceClient, TCLIServiceClientBase, OpenSession, CloseSession, GetInfo, ExecuteStatement, GetTypeInfo, GetCatalogs, GetSchemas, GetTables, GetTableTypes, GetColumns, GetFunctions, GetOperationStatus, CancelOperation, CloseOperation, GetResultSetMetadata, FetchResults, GetDelegationToken, CancelDelegationToken, RenewDelegationToken # service TCLIService

include("HS2_constants.jl")
include("HS2_types.jl")
include("HS2_impl.jl")  # server methods to be hand coded
include("TCLIService.jl")


end # module HS2
