#
# Autogenerated by Thrift Compiler (1.0.0-dev)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

const PRIMITIVE_TYPES = union!(Set{Int32}(), Int32[  Int32(0),   Int32(1),   Int32(2),   Int32(3),   Int32(4),   Int32(5),   Int32(6),   Int32(7),   Int32(8),   Int32(9),   Int32(15),   Int32(16),   Int32(17),   Int32(18),   Int32(19),   Int32(20),   Int32(21)
])
const COMPLEX_TYPES = union!(Set{Int32}(), Int32[  Int32(10),   Int32(11),   Int32(12),   Int32(13),   Int32(14)
])
const COLLECTION_TYPES = union!(Set{Int32}(), Int32[  Int32(10),   Int32(11)
])
const TYPE_NAMES = Dict(
  Int32(0) => Compat.String("BOOLEAN"),
  Int32(1) => Compat.String("TINYINT"),
  Int32(2) => Compat.String("SMALLINT"),
  Int32(3) => Compat.String("INT"),
  Int32(4) => Compat.String("BIGINT"),
  Int32(5) => Compat.String("FLOAT"),
  Int32(6) => Compat.String("DOUBLE"),
  Int32(7) => Compat.String("STRING"),
  Int32(8) => Compat.String("TIMESTAMP"),
  Int32(9) => Compat.String("BINARY"),
  Int32(10) => Compat.String("ARRAY"),
  Int32(11) => Compat.String("MAP"),
  Int32(12) => Compat.String("STRUCT"),
  Int32(13) => Compat.String("UNIONTYPE"),
  Int32(15) => Compat.String("DECIMAL"),
  Int32(16) => Compat.String("NULL"),
  Int32(17) => Compat.String("DATE"),
  Int32(18) => Compat.String("VARCHAR"),
  Int32(19) => Compat.String("CHAR"),
  Int32(20) => Compat.String("INTERVAL_YEAR_MONTH"),
  Int32(21) => Compat.String("INTERVAL_DAY_TIME")
)
const CHARACTER_MAXIMUM_LENGTH = Compat.String("characterMaximumLength")
const PRECISION = Compat.String("precision")
const SCALE = Compat.String("scale")
